//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSeriesDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string message { get; set; }
        public Nullable<int> targetid { get; set; }
    }
}
